raclabboratories/my_site/urls.py
from django.urls import path
from . import views

app_name='my_site'

urlpatterns = [
    path('',views.PostListView.as_view(),name="index"),
    path('new_post/',views.PostCreateView.as_view(),name="new_post"),
    path('products/',views.ProductsView.as_view(),name="products"),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name="post_details"),
    path('order/',views.OrderListView.as_view(),name="order_details"),
    path('post/<int:pk>/add_order',views.add_order,name="add_order"),
]

raclabboratories/raclabboratories/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('my_site.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

raclabboratories/my_site/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

# Create your models here.
class Post(models.Model):
    impurity_name = models.CharField(max_length=1024,unique=True)
    chemical_name = models.CharField(max_length=512)
    cas_no = models.CharField(max_length=128)
    quantity = models.DecimalField(decimal_places=2,max_digits=10)
    current_price = models.DecimalField(decimal_places=2,max_digits=10)
    actual_price = models.DecimalField(decimal_places=2,max_digits=10)
    image_file = models.ImageField(upload_to="impurities")

    def __str__(self):
        return self.impurity_name

    def get_absolute_url(self):
        return reverse("my_site:post_list")

class PostDetails(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="post_details")
    solubility = models.CharField(max_length=256)
    expiry_date = models.DateField()
    purity = models.DecimalField(decimal_places=2,max_digits=4)
    place = models.CharField(max_length=512)
    state = models.CharField(max_length=333,blank=True)
    mol_wt = models.CharField(max_length=333,blank=True)
    mol_fm = models.CharField(max_length=111,blank=True)
    
    def __str__(self):
        return self.post.impurity_name

class Order(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="orders")
    name = models.CharField(max_length=512)
    mobile = models.CharField(max_length=521,help_text = "Default extension (+91).\nPlease enter the pin-code in case of telephone")
    email = models.EmailField(max_length=256,help_text="We dont spam you..!!")
    place = models.CharField(max_length=512,blank=True)
    description = models.TextField(max_length=11111,blank=True)
    datetime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name +" "+ str(self.datetime)
    

raclabboratories/my_site/forms.py
from django import forms
from . import models

def setAttrs(placeholder,classname = 'form-control col-lg-8',type2="text",**kwargs):
    attrs = {'class':classname,'type':type2,'placeholder':placeholder}
    if kwargs:
        for key,value in kwargs.items():
            attrs[key] = value
    return attrs


class PostForm(forms.ModelForm):
    class Meta():
        model = models.Post
        fields = ('impurity_name','cas_no','quantity','current_price','actual_price','image_file')

        widgets = {
            'impurity_name':forms.TextInput(attrs=setAttrs(placeholder='Impurity Name')),
            'cas_no' : forms.TextInput(attrs=setAttrs(placeholder='CAS Number')),
        }

class OrderForm(forms.ModelForm):
    class Meta():
        model = models.Order
        fields = ('name','email','mobile','place','description')

        widgets = {
            'name':forms.TextInput(attrs=setAttrs(placeholder='Full Name')),
            'place' : forms.TextInput(attrs=setAttrs(placeholder='Your Place')),
            'description':forms.Textarea(attrs=setAttrs(placeholder='Any Other queires....',rows="3")),
        }

raclabboratories/my_site/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from . import forms
from datetime import date
from .filters import PostFilter
from django.template import Context
from django.views.generic.edit import FormMixin


class PostListView(ListView):
    model = models.Post

    def get_context_data(self, *args, **kwargs):
        post_names = models.Post.objects.order_by('impurity_name')
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        names = {}
        for post_name in post_names:
            names[post_name.impurity_name] = post_name.id
        # myFilter = PostFilter(self.request.GET, queryset=post_names)
        # print(myFilter.request)
        # post_names = myFilter.qs
        if(len(post_names) > 6):
            post_names = post_names[0:6]
        context['names'] = names
        context['post_names'] = post_names
        # context['myFilter'] = myFilter
        return context

    template_name = "index.html"


class ProductsView(ListView):
    model = models.Post

    def get_context_data(self, *args, **kwargs):
        post_names = models.Post.objects.order_by('impurity_name')
        context = super(ProductsView, self).get_context_data(*args, **kwargs)
        names = {}
        for post_name in post_names:
            names[post_name.impurity_name] = post_name.id
        myFilter = PostFilter(self.request.GET, queryset=post_names)
        post_names = myFilter.qs
        context['names'] = names
        context['post_list'] = post_names
        context['myFilter'] = myFilter
        return context

    template_name = "my_site/products.html"


class PostCreateView(CreateView):
    model = models.Post
    form_class = forms.PostForm
    template_name = "my_site/post_form.html"


class PostDetailView(DetailView):
    model = models.Post
    template_name = "my_site/post_details.html"


class OrderListView(LoginRequiredMixin, ListView):
    login_url = '/admin'
    model = models.Post
    template_name = "my_site/order_list.html"
    context_object_name = "posts"


def add_order(request, pk):
    posts = get_object_or_404(models.Post, pk=pk)
    if request.method == "POST":
        form = forms.OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.post = posts
            order.datetime = date.today()
            order.save()
            return redirect('my_site:post_list')
    else:
        form = forms.OrderForm()
    return render(request, 'my_site/order_form.html', {'form': form, 'post': posts})

raclabboratories/my_site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>RAC LABBORATORIES</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="../../media/img/rac-logo.png" />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Third party plugin CSS-->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/styles.css' %}"
    />
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Navigation-->
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top py-3"
      id="mainNav"
    >
      <div class="container">
        <img
          src="../../media/img/rac-logo.png"
          class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}"
          style="width: 50px; height: 50px; margin-right: 15px;"
        />
        <a
          class="navbar-brand js-scroll-trigger"
          href="{%url 'my_site:index'%}"
          style="color: rgb(245, 222, 12);"
          >RAC LABBORATORIES</a
        >
        <div class="collapse navbar-collapse" id="navbarResponsive"></div>
      </div>
    </nav>
  </head>
  <body id="page-top" style="padding-top: 5.8rem;">
    {%block body_block%} {%endblock%}    
  </body>
  <footer class="page-footer font-small pt-4 bg-dark text-white sticky-bottom">
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
      <!-- Grid row -->
      <div class="row">
        <!-- Grid column -->
        <div class="offset-md-3 col-md-4 mt-md-0 mt-3">
          <!-- Content -->
          <h5 class="text-uppercase" style="color: rgb(245, 222, 12);">rac Labboratories</h5>
          <p>
            Balanagar, Hyderabad. 
            <br>
            <i class="fa fa-phone" aria-hidden="true"></i> 8106401985
            <br>
            <i class="fas fa-mail-bulk"></i> chanderg16@gmail.com
          </p>
        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3" />

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
          <!-- Links -->
          <h5 class="text-uppercase text-info">Links</h5>

          <ul class="list-unstyled">
            <li>
              <a href="{%url 'my_site:index'%}">Home</a>
            </li>
            <li>
              <a href="{%url 'my_site:products'%}">Products</a>
            </li>
          </ul>
        </div>
        <!-- Grid column -->

        
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center text-muted text-small py-3">
      © 2020 Copyright:
      <a> Vasudeva Gudimalla</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <!-- Core theme JS-->
  <script src='{% static "js/scripts.js" %}'></script>
</html>

raclabboratories/my_site/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>RAC LABBORATORIES</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="../../media/img/rac-logo.png" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet"  type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <img src="../../media/img/rac-logo.png" class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" style="width: 50px; height: 50px; margin-right: 15px;">
                <a class="navbar-brand js-scroll-trigger" href="#page-top" style="color: rgb(245, 222, 12);">RAC LABBORATORIES</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Products</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase font-weight-bold" style="color: rgb(245, 222, 12);">RAC LABBORATORIES</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">We supply impurities</p>
                        <form class="form-inline" method="get" >
                            <div class="input-group md-form form-sm form-1 pl-0 col-sm-12" >
                                <div class="input-group-prepend" >
                                  <span class="input-group-text purple lighten-3" id="basic-text1"><i class="fas fa-search text-black"
                                      aria-hidden="true"></i></span>
                                </div>
                                <input type="text" name="impurity_name" id="id_impurity_name" class="form-control my-0 py-1 dropdown-toggle" placeholder="Search" data-toggle="dropdown" style="height: 3rem;">
                                <div id='suggestions' class="dropdown-menu col-sm-11" aria-labelledby="dropdownMenuButton">
                                   
                                </div>
                            </div>
                          </form>
                          
                    </div>
                </div>
            </div>
        </header>
        <!-- Products-->
        <section class="page-section bg-primary" id="about">
            
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">These are the trending products available with us...!!</p>
                        <div class="row">
                            {%if post_names%}
                            {%for post in post_names%}
                              <div class="card bg-light col-sm-4 col-lg-3 col-xl-3" style="margin:2%;box-shadow: 5px 10px 18px #888888; border: 1px solid;min-width: 15rem; max-width: 22rem;">
                                <img src="/media/{{post.image_file}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <h5 class="card-title">{{post.impurity_name}}</h5>
                                  <p class="card-text">
                                      <table>
                                          <tr>
                                            <td><p><strong>CAS :</strong></td>
                                            <td> {{post.cas_no}}</p></td>
                                          </tr>
                                          <tr>
                                            <td><p><strong>Price :</strong></td>
                                            <td> ₹ {{post.actual_price}}/-</p></td>
                                          </tr>
                                          <tr>
                                            <td><p><strong>Qty :</strong></td>
                                            <td> {{post.quantity}} mg</p></td>
                                          </tr>
                                      </table>
                                  </p>
                                  <hr>
                                  <div class="col-md-4 text-center"> 
                                  <a class="btn btn-primary" href="{%url 'my_site:post_details' pk=post.id%}" role="button">Info</a>
                                  </div>
                                </div>
                              </div>
                            {%endfor%}
                            {%else%}
                            <h5>No data</h5>
                            {%endif%}
                        </div>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="{%url 'my_site:products'%}">All Products</a>
                    </div>
                </div>
           
        </section>
        <!-- Services-->
        <section class="page-section bg-white text-dark" id="services" >
            <div class="container">
                <h2 class="text-center mt-0">At Your Service</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Sturdy Themes</h3>
                            <p class="text-muted mb-0">Our themes are updated regularly to keep them bug free!</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Up to Date</h3>
                            <p class="text-muted mb-0">All dependencies are kept current to keep things fresh.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Ready to Publish</h3>
                            <p class="text-muted mb-0">You can use this design as is, or you can make changes!</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-heart text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Made with Love</h3>
                            <p class="text-muted mb-0">Is it really open source if it's not made with love?</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        <!-- Contact-->
        <section class="page-section bg-warning text-white" id="contact" style="height:91%;">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">Have any queries ? Give us a call or send us an email and we will get back to you as soon as possible!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>(+91) 8106401985</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <a class="d-block" href="mailto:chanderg16gmail.com">chanderg16gmail.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-dark text-white py-5" >
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Vasudeva Gudimalla</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/scripts.js" %}'></script>
    </body>
    <script>

    function getMatchings(matchStr, names) {
      let matchedNames = Array(5);
      let matchedHTML = "";
      if (matchStr != " " && matchStr.length > 3) {
        let i = 0;
        for (var name of names) {
          if (name.toLowerCase().indexOf(matchStr.toLowerCase()) >= 0) {
            matchedNames[i++] = name.trim();
          }
          if (i == 5) break;
        }
        i = 1;
        for (var name of matchedNames) {
         
          if (name != undefined){
            let id = Number.parseInt(name.split(":")[1].trim())
            href = '/post/'+id+'/'
            matchedHTML +=
              '<a href='+href+'  class="dropdown-item" type="submit" onmouseover="searchMouseOver()" >' +
              name.split(":")[0] +
              "</a>";
          }
            
        }
      }
      $("#suggestions").html(matchedHTML);
    }

    $("#id_impurity_name").on("keyup", (event) => {
      let users = "{{names|escapejs|safe }}";
      names = users.replace(/[\[\]{}']/g, "").split(",");
      getMatchings(event.target.value, names);
    });

    function searchMouseOver() {
      $("#id_impurity_name").val($(event.target).text());
      console.log($(event.target).text());
    }
    </script>
</html>

raclabboratories/my_site/templates/my_site/order_form.html
{%extends "base.html"%}
{%block body_block%}
<div class="container" style="padding-bottom: 5px;">
    <div class="row">
        <div class="col-md-6">
            <h4 style="text-decoration: underline;">Order details :</h4>
            <img class="img-thumbnail" src="/media/{{post.image_file}}">
              <div class="card-body">
                <h4 class="card-title">{{post.impurity_name}}</h4>
                <p class="card-text" style="color: rgb(216, 148, 59);"> {{post.chemical_name}} </p>
                <p style="color:rgb(4, 145, 145);"><strong>CAS NO : </strong><span >{{post.cas_no}}</span></p>
                <p style="font-size: larger;"><span style="color: red"><strong>Price : </strong>&nbsp;&nbsp;₹ {{post.current_price}}/-</span>&nbsp;&nbsp; <del style="color: slategray;">₹ {{post.actual_price}}/-</del></p>
              </div>
        </div>
        <form class="col-md-6" method="post">
            {%csrf_token%}
            {%for field in form%}
            <div class="form-group">
                <label>{{field.label}}</label>
                {{field}}
                <small id="helpId" class="text-muted">{{field.help_text}}</small>
            </div>
            {%endfor%}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    
    </div>
</div>
<script>
    $("#id_email").attr({'class':"form-control col-lg-8",'placeholder':'Your Email'})
    $("#id_mobile").attr({'class':"form-control col-lg-8",'placeholder':'Phone Number'})
</script>
{%endblock%}

raclabboratories/my_site/templates/my_site/post_details.html
{%extends "base.html"%} {%block body_block%}
<div class="container" >
    <h2 class="text-center" style="color: dimgray; text-decoration: underline;" >{{post.impurity_name|upper}}</h2>
    <div class="row" style="margin-top: 20px;">
        <img src="/media/{{post.image_file}}" class="img-thumbnail offset-md-3 col-md-3" alt="..." />  
        <div class="offset-md-1">
            <br><br>
            <p style="font-size: larger;"><span style="color: red"><strong>Price : </strong>&nbsp;&nbsp;₹ {{post.current_price}}</span>&nbsp;&nbsp; <del style="color: slategray;">₹ {{post.actual_price}}</del></p>
            <a class="btn btn-success" href="{%url 'my_site:add_order' pk=post.id%}" role="button">Enquire</a>
        </div>
    </div>
    <hr>
    <h4 style="text-decoration: underline;">Product Details:-</h4>
    
    <table class="table table-striped table-bordered offset-md-1 col-md-10" style="margin-top: 40px;">
        <tbody>
            {%for p in post.post_details.all%}
            <tr>
                <td style="min-width: 170px;font-weight: bold;">Chemical Name</td>
                <td>{{post.chemical_name}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >CAS NO</td>                
                <td>{{post.cas_no}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >Formula</td>                
                <td>{{p.mol_fm|upper}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >Molecular Weight</td>                
                <td>{{p.mol_wt|upper}}</td>
            </tr>
            <tr>
                <td class="font-weight-bold">Solubility</td>                
                <td>{{p.solubility}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >State</td>                
                <td>{{p.state|upper}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >Purity</td>                
                <td>{{p.purity}} %</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >Quantity</td>                
                <td>{{post.quantity}}</td>
            </tr>
            <tr>
                 <td  class="font-weight-bold" >Exipry</td>                
                <td>{{p.expiry_date}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
</div>
 {%endblock%}

raclabboratories/my_site/templates/my_site/post_form.html
{%extends "base.html"%}

{%block body_block%}

<div class="container">
  
    <form enctype="multipart/form-data" method="post">
        {%csrf_token%}
        {%for field in form%}
        <div class="form-group">
          <label for="">{{field.label}}</label>
          {{field}}
          <small id="helpId" class="text-muted">{{field.help_text}}</small>
        </div>
        {%endfor%}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>   
</div>
<script>
    $("#id_quantity").attr({"class":"form-control col-lg-2","placeholder":"In Milligrams"})
    $("#id_current_price").attr({"class":"form-control col-lg-2","placeholder":"Offer Price"})
    $("#id_actual_price").attr({"class":"form-control col-lg-2","placeholder":"Actual Price"})
    
</script>
{%endblock%}

raclabboratories/my_site/templates/my_site/post_list.html
{%extends "base.html"%} 

{%block body_block%}
<div class="container">
  <div class="jumbotron">
    <h1 class="display-3">RAC Labboratories</h1>
    <p class="lead">API impurites</p>
    <hr class="my-2">
    <p>Brief about the company</p>
  </div>
  <div class="row col-md-12">    
    <form class="form-inline" method="get">
      <div class="dropdown">
        {%for field in myFilter.form%}
        {{field}}
        {%endfor%}
        <div id='suggestions' class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        </div>
      </div>
    </form>
  </div>
  <div class="row">
      {%if post_names%}
      {%for post in post_names%}
        <div class="card bg-light col-md-4 col-lg-4 col-xl-3" style="margin:2%;box-shadow: 5px 10px 18px #888888; border: 1px solid;">
          <img src="/media/{{post.image_file}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{post.impurity_name}}</h5>
            <p class="card-text">
                <table>
                    <tr>
                      <td><p><strong>CAS :</strong></td>
                      <td> {{post.cas_no}}</p></td>
                    </tr>
                    <tr>
                      <td><p><strong>Price :</strong></td>
                      <td> ₹ {{post.actual_price}}/-</p></td>
                    </tr>
                    <tr>
                      <td><p><strong>Qty :</strong></td>
                      <td> {{post.quantity}} mg</p></td>
                    </tr>
                </table>
            </p>
            <hr>
            <div class="col-md-4 text-center"> 
            <a class="btn btn-primary" href="{%url 'my_site:post_details' pk=post.id%}" role="button">Info</a>
            </div>
          </div>
        </div>
      {%endfor%}
      {%else%}
      <h5>No data</h5>
      {%endif%}
  </div>
</div>
<script>
  function getMatchings(matchStr, names) {
      let matchedNames = Array(5);
      let matchedHTML = "";
      if (matchStr != " " && matchStr.length > 3) {
        let i = 0;
        for (var name of names) {
          console.log(name)
          if (name.toLowerCase().indexOf(matchStr.toLowerCase()) >= 0) {
            matchedNames[i++] = name.trim();
          }
          if (i == 5) break;
        }
        i = 1;
        for (var name of matchedNames) {
         console.log(name)
          if (name != undefined)
            matchedHTML +=
              '<button  class="dropdown-item" type="submit" onmouseover="searchMouseOver()" >' +
              name +
              "</button>";
        }
      }
      $("#suggestions").html(matchedHTML);
    }

 // <!-- <input class="dropdown-toggle" type="text" data-toggle="dropdown"   /> -->
    $("#id_impurity_name").attr({ class: "form-control  dropdown-toggle", placeholder: "Search",type:'text',"data-toggle":"dropdown" });

    $("#id_impurity_name").on("keyup", (event) => {
      let users = "{{names|escapejs|safe }}";
      names = users.replace(/[\[\]']/g, "").split(",");
      getMatchings(event.target.value, names);
    });

    function searchMouseOver() {
      $("#id_impurity_name").val($(event.target).text());
      console.log($(event.target).text());
    }
</script>
{%endblock%}