my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from my_site import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include("my_site.urls")),
    path('accounts/login/',auth_views.LoginView.as_view(),name="login"),    
    path('accounts/logout/',views.DoLogout.as_view(),name="logout"),
    path('signup/',views.SignUpView.as_view(),name="signup"),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/my_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'my_site'
urlpatterns = [
    path('', views.IndexPage.as_view(), name="index"),
    path('posts/',views.PostListView.as_view(),name="post_list"),
    path('newpost/', views.NewPost.as_view(), name="new_post"),
    path("posts/<int:pk>/",views.PostDetailView.as_view(),name="post_detail"),
    path("posts/<int:pk>/update/",views.PostUpdateView.as_view(),name="update_detail"),
    path("posts/<int:pk>/delete/",views.PostDeleteView.as_view(),name="delete_detail"),
    path("posts/<int:pk>/comment",views.add_comment,name="add_comment"),
    path("comment/<int:pk>/delete",views.remove_comment,name="delete_comment"),
]

my_blog/my_site/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    image_file = models.ImageField(upload_to="post_pics")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("my_site:post_detail",kwargs={'pk':self.pk})

class Comment(models.Model):
    comment = models.CharField(max_length=512)
    author = models.CharField(max_length=512)
    post = models.ForeignKey(Post,related_name="comments",on_delete=models.CASCADE)

    def __str__(self):
        return self.author

my_blog/my_site/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper


def setAttrs(attrType, placeholder, **kwargs):
    tempAttrs = {'class': 'form-control col-lg-5',
                 'type': attrType, 'placeholder': placeholder}
    if kwargs:
        for key, value in kwargs.items():
            tempAttrs[key] = value
        return tempAttrs
    else:
        return tempAttrs


class NewPostForm(forms.ModelForm):
    class Meta():
        model = models.Post
        fields = ['title', "description","image_file"]
        widgets = {
            'title': forms.TextInput(
                attrs=setAttrs('text', 'Enter Title')
            ),
            'description': forms.Textarea(
                attrs=setAttrs(
                    'textarea', 'Enter few words . . . . . .', rows="5")
            )
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model = models.Comment
        fields = ['author', 'comment']
        widgets = {
            'author': forms.TextInput(
                attrs=setAttrs('text', 'Your Name')
            ),
            'comment': forms.Textarea(
                attrs=setAttrs('textarea','Enter Comment',rows=2)
            )
        }


class SignUpForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('username','first_name', 'last_name','email' )
        widgets = {
            'username':forms.TextInput(attrs=setAttrs("text","Username")),
            'first_name': forms.TextInput(attrs=setAttrs("text","First Name")),
            'last_name':  forms.TextInput(attrs=setAttrs("text","Last Name")),
            'email' :  forms.EmailInput(attrs=setAttrs("email","Your Email ID")),
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['password1'].widget.attrs = setAttrs("password","Password")
        self.fields['password2'].widget.attrs = setAttrs("password","Re-enter Password")

my_blog/my_site/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView,)
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . import models
from . import forms
from django.urls import reverse_lazy

# Create your views here.

class IndexPage(TemplateView):
    template_name = "index.html"

class PostListView(ListView):
    model = models.Post
    template_name = "post_list.html"

class NewPost(LoginRequiredMixin,CreateView):
    login_url = "/accounts/login/"
    form_class = forms.NewPostForm
    model = models.Post
    template_name = "post_form.html"

class PostDetailView(LoginRequiredMixin,DetailView):
    login_url = "/accounts/login/"
    model = models.Post
    template_name = "post_details.html" 
    
class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = "/accounts/login/"
    model = models.Post
    form_class = forms.NewPostForm
    template_name = "post_form.html"

class PostDeleteView(LoginRequiredMixin,DeleteView):
    login_url = "/accounts/login/"
    model = models.Post
    template_name = 'post_confirm_delete.html'
    success_url = reverse_lazy("my_site:post_list")

class DoLogout(LoginRequiredMixin,LogoutView):
    def get(self, request):
        return redirect("my_site:post_list")

class SignUpView(CreateView):
    form_class = forms.SignUpForm
    model = User
    template_name = 'signupForm.html'
    success_url = '/'

def add_comment(request,pk):
    post = get_object_or_404(models.Post,pk=pk)
    if request.method == "POST":
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('my_site:post_detail', pk=post.pk)
    else:
        form = forms.CommentForm()
    return render(request,'comment_form.html',{'form':form})

def remove_comment(request,pk):
    comment = get_object_or_404(models.Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('my_site:post_detail', pk=post_pk)

my_blog/my_site/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </head>
  <body style="padding: 65px;">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'my_site:index' %}">BLOG</a>
      <button
        class="navbar-toggler d-lg-none"
        type="button"
        data-toggle="collapse"
        data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId"
        aria-expanded="false"
        aria-label="Toggle navigation"
      ></button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
        {% if user.is_authenticated %}
        <ul class="nav justify-content-center">
          <li class="nav-item" style="color: blue;">
            <a class="nav-link" >Welcome {{user.username}}</a>
          </li>
        </ul>
        {%endif%}
          
        <ul class="navbar-nav justify-content-end">
          <li class="nav-item">
            <a id="nav1" class="nav-link" href="{% url 'my_site:post_list' %}">Posts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a id="nav2" class="nav-link" href="{% url 'my_site:new_post' %}">New Post</a>
          </li>
          <li class="nav-item">
            <a id="nav3" class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {%else%}
          <li class="nav-item">
            <a id="nav4" class="nav-link" href="{% url 'login'%}">Login</a>
          </li>
          <li class="nav-item">
            <a id="nav5" class="nav-link" href="{% url 'signup'%}">Signup</a>
          </li>
          
          {%endif%}
        </ul>
      </div>
    </nav>
    {%block body_block%} {%endblock%}
  </body>
  <script>
    var path = window.location.pathname;
    console.log(path);
    if (path.includes("posts")) {
      $("#nav1").addClass("active")
    }
    if (path.includes("newpost")) {
      $("#nav2").addClass("active")
    }
    if (path.includes("login")) {
      $("#nav4").addClass("active")
    }
    if (path.includes("signup")) {
      $("#nav5").addClass("active")
    }
  </script>
</html>

my_blog/my_site/templates/comment_form.html
{%extends 'base.html'%} {%block body_block%}
<h5>Comment form</h5>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{%endblock%}

my_blog/my_site/templates/index.html
{%extends 'base.html'%} 

{%block body_block%}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple blog page, that has the information of the places you visited</p>
        <hr class="my-4">
        <p>You can add the places and write about them.</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{%url 'my_site:post_list'%}" role="button">Places</a>
        </p>
      </div>
</div>
{%endblock%}

my_blog/my_site/templates/post_confirm_delete.html
{%extends 'base.html'%} 

{%block body_block%}

<div class="container">
    <div class="card text-dark col-md-4 col-lg-4 " style="margin-top: 2%; box-shadow: 5px 10px 18px #888888;;">
        <img src="/media/{{post.image_file}}" class="card-img-top" alt="..." style="width: 100%;height: 60%;" />
        <div class="card-body">
          <h5 class="card-title">Are you sure, you want to delete {{post.title}} ?</h5>
          <form method="post">
            {% csrf_token %}
              <input class='btn btn-danger' type="submit" value="Confirm" />
              <a href="{% url 'my_site:post_detail' pk=post.id  %}" class="btn btn-primary">Cancel</a>
          </form>
          
        </div>
      </div>
</div>
{%endblock%}

my_blog/my_site/templates/post_details.html
{%extends 'base.html'%} {%block body_block%}
<div
  class="card bg-info offset-lg-2 col-lg-7 align-self-center"
  style="margin-top: 10px; margin-bottom: 5px;"
>
  <img
    src="/media/{{post.image_file}}"
    class="card-img-top"
    style="width: 100%; height: 400px;"
  />
  <div class="card-body">
    <h4 class="card-title">{{post.title|upper}}</h4>
    <hr />
    <p class="card-text text-white">{{post.description}}</p>
    <hr />
    <div class="card-body">
      <a
        name=""
        id=""
        class="btn btn-warning"
        href="{% url 'my_site:update_detail' pk=post.id %}"
        role="button"
        >Update</a
      >
      <a
        name=""
        id=""
        class="btn btn-danger"
        href="{% url 'my_site:delete_detail' pk=post.id %}"
        role="button"
        >Delete</a
      >
    </div>
  </div>
</div>
<a href="{% url 'my_site:add_comment' pk=post.id%}" class="btn btn-primary text-white offset-lg-2 btn-md col-xs-2" role="button">Comment</a>

{%if post.comments.all%}
<h5 class="offset-lg-2 row-2" style="color:steelblue;margin-top: 5px; margin-bottom: 5px;">Total Comments : <strong style="color: black;">{{post.comments.all|length}}</strong></h5>
<div
  class="card bg-light offset-lg-2 col-lg-7 align-self-center"
  style="margin-top: 10px;"
>
  <div class="card-body">
    <h4 class="card-title">Comments</h4>
    {%for comment in post.comments.all%}
    <hr />
    <h5 style="color: steelblue;">{{comment.author}}</h5>
    <p style="color: rgb(150, 142, 142);">{{comment.comment}}</p> 
    <a href="{%url 'my_site:delete_comment' pk=comment.pk%}"><i class="fa fa-trash" aria-hidden="true" style="color: red;"></i></a>
    {%endfor%}
  </div>
</div>
{%else%}
<h5 class="offset-lg-2 row-2" style="color:steelblue;margin-top: 5px; margin-bottom: 5px;">Total Comments : <strong style="color: black;">0</strong></h5>
{%endif%}
{%endblock%}

my_blog/my_site/templates/post_form.html
{%extends 'base.html'%} 

{%block body_block%}
<h1>Post Form</h1>
<form class="form-horizontal" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {%for field in form%}
      <div class="form-group">
        <label for="name">{{field.label}}</label>
        {{field}}
      </div>
    {%endfor%}
    <button type="submit" class="btn btn-primary ">Submit</button>
</form>

{%endblock%}

my_blog/my_site/templates/post_list.html
{%extends 'base.html'%} 
{%block body_block%}
<div class="row">
    {%for post in post_list%}
    <div class="card text-dark col-md-4 col-lg-3 " style=" margin: 2%; box-shadow: 5px 10px 18px #888888;;">
      <img src="/media/{{post.image_file}}" class="card-img-top" alt="..." style="width: 100%;height: 60%;" />
      <div class="card-body text-center">
        <h5 class="card-title">{{post.title}}</h5>
        <a href="{% url 'my_site:post_detail' pk=post.id  %}" class="btn btn-primary">Info</a>
      </div>
    </div>
    {%endfor%}
  </div>
{%endblock%}

my_blog/my_site/templates/signupForm.html
{% extends "base.html" %} {%block body_block%}
<form method="post">
  {%for field in form%} {% for error in field.errors %}
  <div class="alert alert-danger alert-dismissible fade show col-lg-5" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    <strong>{{ error|escape }}</strong>
  </div>
  
  <script>
    $(".alert").alert();
  </script>
  {% endfor %} {%endfor%} {%for field in form%} {% csrf_token %}

  <div class="form-group">
    <label for="">{{field.label}}</label>
    {{field}}
    <br />
    <small id="helpId" class="text-muted">{{field.help_text}}</small>
  </div>
  {%endfor%}
  <input
    name="sumbit"
    id="sumbit"
    class="btn btn-primary"
    type="submit"
    value="Submit"
  />
</form>
{%endblock%}